### ISSUE TITLE
Upgrade to FLAMEGPU v2.0.0-rc

### ISSUE THREAD

**Issue by bytetec** [zeyus/FLAMEGPU2-Prisoners-Dilemma-ABM#13]
Hi zeyus
Will there be an upgrade to the current FLAMEGPU version v2.0.0-rc https://github.com/FLAMEGPU/FLAMEGPU2/tags ?
Some of the function names changed and other significate changes.

Best bytetec

**Comment by zeyus** [comment]
Hey @bytetec , I hadn't considered this prior to you asking but, actually, yeah why not, I really enjoyed working with FLAMEGPU and I've leveled up some skills in other languages so it might be a great time to revisit this and at the very least make it compatible with the RC, if not redactor parts of it too (I'm very aware that some of the code is really smashed together, but it was a tight deadline when I first wrote it! :)

**Comment by zeyus** [comment]
This now runs with FLAMEGPU v2.0.0-rc.

I tested a few different configurations and it works great, in fact, it's faster than I remember so I guess there have been some amazing backend improvements to FLAMEGPU! :)

**Comment by bytetec** [comment]
just tested it on my side and can confirm it works great. thx

**Comment by zeyus** [comment]
Happy to hear it :) let me know if you come across anything else. Happy to know someone is making use of the code!
